import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, DM_Sans } from "next/font/google";
import "./globals.css";

import Providers from "./providers";
import Dashboard from "@/components/myComponents/Dashboard/page";
import { cn } from "@/lib/utils";

const dmSansHeading = DM_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
        dmSansHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col dark">
        <Dashboard>
            <Providers>{children}</Providers>
        </Dashboard>
      </body>
    </html>
  );
}
